server:
  port: 8082

spring:
  application:
    name: chat-service

  data:
    mongodb:
        uri: mongodb://root:rootpassword@localhost:27017/chat-service?authSource=admin
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true