-- -- Define user table
-- CREATE TABLE IF NOT EXISTS public.user (
--     -- User is identified by serial id number
--     id SERIAL PRIMARY KEY,
--
--     -- User has unique username and email
--     username VARCHAR(255) UNIQUE NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--
--     first_name VARCHAR(255) NOT NULL,
--     last_name VARCHAR(255) NOT NULL,
--
--     -- user with unverified email is not active
--     is_active BOOLEAN DEFAULT FALSE,
--
--     -- user with ban flag is prohibited for access to the service
--     is_banned BOOLEAN DEFAULT FALSE,
--
--     -- date of birth is also important to determine the age of user
--     date_of_birth DATE NOT NULL,
--
--     -- Creation and updates are also recorded
--     created_at TIMESTAMPTZ -- (Timezone is set to UTC+4 Tbilisi time globally)
--         DEFAULT CURRENT_TIMESTAMP
-- );