server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 6

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE}
  queue:
    email: ${RABBITMQ_EMAIL_QUEUE}
    push-notification: ${RABBITMQ_PUSH_NOTIFICATION_QUEUE}
  routing-key:
    email: ${RABBITMQ_EMAIL_ROUTING_KEY}
    push-notification: ${RABBITMQ_PUSH_NOTIFICATION_ROUTING_KEY}